# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

parameters:
  - name: severity
    displayName: Define severity (warning/error)
    type: string
    default: 'error'
    values:
      - error
      - warning

steps:
- script:
      '"C:\Program Files\Parasoft\dotTEST\2023.2\dottest\dottestcli.exe" -solution Quartz.sln'
  displayName: 'Run dotTest analysis'
- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    parasoftToolOrJavaRootPath: 'C:\Program Files\Parasoft\dotTEST\2023.2\dottest'
- task: ParasoftStaticAnalysisQualityGate@1
  inputs:
    type: 'total'
    severity: '${{ parameters.severity }}'
    threshold: '300'
    buildStatus: 'failed'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
